export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const ACCESS_KEY = '4HVwCjWoau8W51R2TOkyTDGSZ7tPVoEI-aLCb_vury0';
export const SECRET_KEY = 'z_h6khkhRLBHQ1bhRO5BwYu1aVXCHX_38soC4EY9RKc';
export const REDIRECT_URI = 'http://gallery';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';